### ISSUE TITLE
Komptatibilität Contao 4.13 // compatibility Contao 4.13

### ISSUE THREAD

**Issue by macidev** [contao-themes-shop/vacancy-calendar#7]
Hallo Contao-Themes-Shop, 

ist diese Erweiterung mit der aktuellen LTS von Contao (4.13) kompatibel?
Wenn ja, was muss geändert werden, damit die Erweiterung weiterhin läuft? 

EN: 
Hello Contao-Themes-Shop, 

is this extension compatible with the current LTS of Contao (4.13)?
If so, what needs to be changed so that the extension continues to run?

**Comment by contaoacademy** [comment]
Ich habe die Erweiterung unter Contao 4.13 und PHP 8 im Einsatz. Bei mir läuft die Erweiterung. Wo gibt es bei dir Probleme?

**Comment by macidev** [comment]
@contaoacademy das war eine Vorabfrage, da ich nicht genau wusste, ob sämtliche Anforderungen passen. Da ich das Modul "einfach" installiert habe und es mit PHP 8.2 zu Rande kommt, schließe ich dieses Ticket. Es funktioniert bisher wie gewünscht.
